### ISSUE TITLE
Adding a product to a branch office requires an UUID instead of its name.

### ISSUE THREAD

**Issue by kristjansuligoj** [zabukovnikmaj/podjetje#17]
When adding a branch office, it requires to add a product uuid instead of its name, because checkProducts searches in the item array using the uuid, but a product name is given. Same thing when adding a branch name, while adding an employee.

**Comment by zabukovnikmaj** [comment]
This issues has been fixed by adding checkboxes and/or radio buttons. The feature is currrently waiting to be confirmed as pull request.
