### ISSUE TITLE
Editing a product with an incorrect, but valid UUID, the editing is done, but no effect is made.

### ISSUE THREAD

**Issue by kristjansuligoj** [zabukovnikmaj/podjetje#19]
/products/edit?id=cb91f4f9-5057-410e-8ec8-a52abcde1563 - Exists in the database
/products/edit?id=cb91f4f9-5057-410e-8ec8-a52abcde1562 - Doesnt exist in the database

If you go to the the second URL, it doesn't throw an error, and you can edit a non-existing element. Nothing happens when you save it.

**Comment by zabukovnikmaj** [comment]
The issue has been fixed by raising 404 error.
